version: '2'
services:
  front_end-app:
    image: front_end
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://front_end-mariadb:3306/front_end
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  front_end-mariadb:
    extends:
      file: mariadb.yml
      service: front_end-mariadb
